language: objective-c
osx_image: xcode7.3
script:
  set -o pipefail &&
  xcodebuild build -project LayoutKit.xcodeproj -scheme LayoutKitSampleApp -sdk iphonesimulator9.3
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.3'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4'
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=8.4' &&
  xcodebuild test -project LayoutKit.xcodeproj -scheme LayoutKit -sdk iphonesimulator9.3
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.3'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4'
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=8.4'
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
